version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Port for RabbitMQ
      - "15672:15672" # Port for RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3

  image_processor:
    build:
      context: .
      dockerfile: image_processor/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8000:8000"

  tests:
    build:
      context: ./tests
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - server
      - image_processor