basePath: /
host: localhost:8000
info:
  contact: {}
  description: This is a sample server for managing tasks.
  title: Task Management API
  version: "1.0"
paths:
  /result:
    get:
      consumes:
      - application/json
      description: Retrieve the result of a task by its ID.
      parameters:
      - description: Task ID
        in: query
        name: task_id
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Result of the task
          schema:
            type: string
        "400":
          description: Missing task id
          schema:
            type: string
        "404":
          description: Task not found
          schema:
            type: string
      summary: Get task result
      tags:
      - tasks
  /status:
    get:
      consumes:
      - application/json
      description: Retrieve the status of a task by its ID.
      parameters:
      - description: Task ID
        in: query
        name: task_id
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Status of the task
          schema:
            type: string
        "400":
          description: Missing task id
          schema:
            type: string
        "404":
          description: Task not found
          schema:
            type: string
      summary: Get task status
      tags:
      - tasks
  /task:
    post:
      consumes:
      - application/json
      description: Creates a new task and returns the task ID.
      produces:
      - application/json
      responses:
        "201":
          description: Task ID
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request
          schema:
            type: string
        "500":
          description: Failed to add task
          schema:
            type: string
      summary: Create a new task
      tags:
      - tasks
schemes:
- http
swagger: "2.0"
